DROP TABLE IF EXISTS meals;

CREATE TABLE meals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    country TEXT,
    description TEXT,
    ingredients TEXT,
    calories INTEGER,
    fat REAL,
    carbs REAL,
    sodium REAL,
    protein REAL
);

INSERT INTO meals (name, country, description, ingredients, calories, fat, carbs, sodium, protein) 
VALUES 
('Chicken Tikka Masala', 'India', 'Roasted marinated chicken pieces in a spiced sauce.', 'Chicken, Yogurt, Spices, Tomato, Cream', 380, 12.0, 14.0, 140.0, 48.0),
('Greek Salad', 'Greece', 'Fresh vegetable salad with feta and olive oil.', 'Cucumbers, Tomatoes, Feta, Olives, Olive Oil', 210, 15.0, 9.0, 220.0, 7.0),
('Palak Paneer', 'India', 'Spinach curry with cubed cheese.', 'Spinach, Paneer, Spices, Garlic', 290, 18.0, 12.0, 120.0, 20.0),
('Ghormeh Sabzi', 'Iran', 'A Persian herb stew made with chicken', 'Chicken, Parsley, Cilantro, Chives, Fenugreek, Spinach, Red Kidney Beans, Dried Limes, Olive Oil, Turmeric, Garlic', 280, 8.0, 38.0, 95.0, 15.0),
('Shirazi Salad', 'Iran', 'Diced cucumber and tomato salad tossed in a vinaigrette.', 'Cucumbers, Tomatoes, Red Onion, Fresh Mint, Extra Virgin Olive Oil, Lime Juice, Black Pepper', 90, 5.0, 10.0, 15.0, 2.0),
('Dal Tadka', 'India', 'Yellow lentils with turmeric and garlic.', 'Toor Dal, Tomatoes, Garlic, Ginger, Cumin, Mustard Seeds, Avocado Oil, Lemon Juice, Turmeric', 230, 4.5, 36.0, 80.0, 13.0),
('Chana Masala', 'India', 'Chickpeas cooked in a tomato, onion, and warm spice sauce.', 'Chickpeas, Tomatoes, Onions, Garlic, Ginger, Chana Masala Spice Blend, Olive Oil, Lemon Juice, Cilantro', 280, 5.0, 45.0, 110.0, 14.0),
('Rajma Masala', 'India', 'Kidney bean curry cooked in tomato gravy.', 'Red Kidney Beans, Tomatoes, Onions, Garlic, Ginger, Cumin, Garam Masala, Olive Oil, Fresh Coriander', 290, 5.0, 48.0, 105.0, 16.0),

('Greek Briam', 'Greece', 'Roasted vegetables with olive oil.', 'Zucchini, Potatoes, Eggplant, Tomatoes, Red Onion, Olive Oil, Garlic, Oregano, Black Pepper', 210, 9.0, 30.0, 45.0, 5.0),
('Gigantes Plaki', 'Greece', 'Baked giant white beans in tomato and herb sauce.', 'Lima Beans, Tomatoes, Olive Oil, Garlic, Onions, Parsley, Lemon Juice', 280, 8.0, 42.0, 85.0, 13.0),
('Ropa Vieja de Pollo', 'Cuba', 'Shredded chicken breast with bell peppers and onions.', 'Chicken Breast, Bell Peppers, Onions, Garlic, Tomatoes, Olive Oil, Cumin, Lime Juice', 290, 7.0, 12.0, 130.0, 42.0),
('Chicken Fajitas', 'Mexico', 'Chicken strips with bell peppers and spices.', 'Chicken Breast, Bell Peppers, Onions, Olive Oil, Lime Juice, Cumin, Chili Powder, Garlic', 310, 9.0, 14.0, 120.0, 41.0),
('Ceviche', 'Peru', 'Raw white fish citrus juices.', 'White Fish, Lime Juice, Red Onion, Cilantro, Chili Peppers, Sweet Potato', 190, 2.5, 16.0, 110.0, 26.0),
('Solterito de Quinua', 'Peru', 'Quinoa salad with vegetables and citrus dressing.', 'Quinoa, Tomatoes, Corn, Red Onion, Olive Oil, Lime Juice, Cilantro', 260, 7.0, 41.0, 40.0, 9.0),
('Poulet Aux Noix', 'Haiti', 'Chicken with raw cashews and Creole spices.', 'Chicken Breast, Raw Cashews, Bell Peppers, Tomatoes, Garlic, Lime Juice, Olive Oil, Thyme', 360, 14.0, 15.0, 135.0, 43.0),
('Asopao De Pollo', 'Puerto Rico', 'Chicken and brown rice soup with vegetables.', 'Chicken Breast, Brown Rice, Tomatoes, Bell Peppers, Garlic, Cilantro, Olive Oil, Oregano', 320, 6.0, 36.0, 140.0, 31.0),
('Moqueca de Peixe', 'Brazil', 'White fish and bell pepper stew in light coconut milk.', 'White Fish, Bell Peppers, Tomatoes, Onions, Light Coconut Milk, Lime Juice, Cilantro, Olive Oil', 290, 11.0, 12.0, 125.0, 34.0),
('Ajiaco Bogotano', 'Colombia', 'Chicken soup with potatoes, corn, and guascas herbs.', 'Chicken Breast, Potatoes, Corn, Guascas, Garlic, Green Onions, Avocado', 310, 6.0, 38.0, 115.0, 28.0),
('Jerk Chicken', 'Jamaica', 'Grilled chicken  in spicy herbs and citrus.', 'Chicken Breast, Allspice, Scotch Bonnet, Garlic, Ginger, Thyme, Lime Juice, Olive Oil', 280, 8.0, 6.0, 130.0, 44.0),
('Tuscan Ribollita', 'Italy', 'Vegetable and white bean soup and with whole grain bread.', 'Cannellini Beans, Kale, Cabbage, Tomatoes, Carrots, Celery, Whole Grain Bread, Olive Oil', 260, 6.0, 41.0, 140.0, 12.0),
('Mercimek Çorbası', 'Turkey', 'Red lentil soup with lemon and spices.', 'Red Lentils, Onions, Carrots, Garlic, Cumin, Olive Oil, Lemon Juice, Mint', 220, 4.0, 36.0, 75.0, 13.0),
('Misir Wat', 'Ethiopia', 'Spicy red lentils in berbere spice.', 'Red Lentils, Onions, Garlic, Ginger, Berbere Spice, Olive Oil, Tomato Paste', 240, 5.0, 38.0, 85.0, 14.0),
('Atakilt Wat', 'Ethiopia', 'Cabbage, carrots, and potatoes with turmeric.', 'Cabbage, Carrots, Potatoes, Onions, Garlic, Ginger, Turmeric, Olive Oil', 170, 4.5, 30.0, 35.0, 4.0),
('Harira', 'Morocco', 'Lentil and chickpea soup with herbs and lemon.', 'Lentils, Chickpeas, Tomatoes, Celery, Cilantro, Parsley, Ginger, Cinnamon, Lemon Juice', 250, 3.5, 43.0, 110.0, 13.0),
('Ojja', 'Tunisia', 'Poached eggs in a spicy pepper and tomato sauce.', 'Eggs, Bell Peppers, Tomatoes, Garlic, Harissa, Caraway, Olive Oil', 230, 14.0, 11.0, 150.0, 15.0),
('Sashimi', 'Japan', 'Sliced raw salmon and tuna served with ginger.', 'Raw Salmon, Raw Tuna, Daikon Radish, Fresh Ginger, Lemon Slice', 210, 7.0, 2.0, 70.0, 34.0),
('Garlic Bok Choy', 'China', 'Stir-fried bok choy with garlic and sesame oil.', 'Baby Bok Choy, Garlic, Ginger, Sesame Oil, White Pepper', 80, 4.5, 8.0, 65.0, 4.0),
('Gai Pad Krapow', 'Thailand', 'Stir-fried chicken with basil, chili, and garlic.', 'Ground Chicken Breast, Holy Basil, Garlic, Thai Chili, Lime Juice, Sesame Oil', 270, 8.0, 7.0, 140.0, 40.0),
('Gỏi Gà', 'Vietnam', 'Chicken and cabbage salad with lime dressing.', 'Chicken Breast, Cabbage, Carrots, Mint, Cilantro, Lime Juice, Rice Vinegar, Chili', 220, 4.0, 12.0, 110.0, 32.0),
('Phở Gà', 'Vietnam', 'Chicken noodle soup with  herb broth.', 'Chicken Breast, Rice Noodles, Ginger, Star Anise, Cinnamon, Green Onion, Basil, Lime Juice', 330, 4.5, 44.0, 160.0, 29.0),
('Parippu', 'Sri Lanka', 'Red lentils cooked in light coconut milk and spices.', 'Red Lentils, Light Coconut Milk, Turmeric, Mustard Seeds, Curry Leaves, Chili, Garlic', 230, 6.0, 34.0, 70.0, 11.0),
('Borani Banjan', 'Afghanistan', 'Eggplant and tomatoes with garlic yogurt.', 'Eggplant, Tomatoes, Garlic, Plain Greek Yogurt, Mint, Olive Oil', 190, 8.0, 22.0, 80.0, 8.0),
('Lubya', 'Afghanistan', 'Kidney bean stew with tomatoes and garlic.', 'Red Kidney Beans, Tomatoes, Onions, Garlic, Coriander, Cumin, Olive Oil', 260, 4.0, 44.0, 75.0, 14.0),
('Sabzi', 'Afghanistan', 'Spinach and herbs cooked with garlic and citrus.', 'Spinach, Cilantro, Parsley, Green Onions, Garlic, Olive Oil, Lemon Juice', 140, 7.0, 15.0, 90.0, 6.0),
('Mujadara', 'Lebanon', 'Lentils and brown rice with caramelized onions.', 'Brown Rice, Green Lentils, Onions, Olive Oil, Cumin, Black Pepper', 290, 6.0, 52.0, 50.0, 11.0),
('Polvo à Lagareiro', 'Portugal', 'Roasted octopus with small potatoes, garlic, and olive oil.', 'Octopus, Potatoes, Garlic, Extra Virgin Olive Oil, Parsley, Black Pepper', 340, 11.0, 28.0, 180.0, 32.0),
('Gambas al Ajillo', 'Spain', 'Shrimp in olive oil, garlic, and chili flakes.', 'Shrimp, Garlic, Extra Virgin Olive Oil, Red Chili Flakes, Parsley, Lemon Juice', 220, 11.0, 4.0, 160.0, 26.0),
('Ratatouille', 'France', 'Vegetables with garlic and fresh herbs.', 'Zucchini, Eggplant, Bell Peppers, Tomatoes, Garlic, Olive Oil, Thyme', 160, 7.0, 21.0, 35.0, 4.0),
('Gado Gado', 'Indonesia', 'Steamed vegetables and tofu with light peanut sauce.', 'Tofu, Bean Sprouts, Green Beans, Cabbage, Peanut Butter, Lime Juice, Garlic, Chili', 290, 14.0, 26.0, 130.0, 17.0),
('Prebranac', 'Serbia', 'Baked white bean casserole with onions and paprika.', 'White Beans, Onions, Sweet Paprika, Garlic, Bay Leaf, Olive Oil', 270, 5.0, 46.0, 60.0, 13.0),
('Chicken & Avocado Bowl', 'USA', 'Grilled chicken, quinoa, black beans, and fresh avocado.', 'Chicken Breast, Quinoa, Black Beans, Avocado, Tomatoes, Cilantro, Lime Juice', 380, 12.0, 36.0, 110.0, 36.0),
('Sundubu Jjigae', 'Korea', 'Spicy soft tofu stew with seafood and kimchi.', 'Soft Tofu, Shrimp, Kimchi, Garlic, Green Onions, Gochugaru, Sesame Oil', 230, 8.0, 14.0, 190.0, 24.0),
('Sinigang', 'Philippines', 'Sour tamarind soup with shrimp, radish, and leafy greens.', 'Shrimp, Tamarind Broth, Radish, Water Spinach, Tomatoes, Onions, Garlic, Chili', 210, 3.5, 18.0, 140.0, 26.0),
('Salt & Pepper Squid with Lemon', 'Australia', 'Pan-seared squid seasoned with black pepper, sea salt, and fresh lemon.', 'Squid, Olive Oil, Black Pepper, Garlic, Lemon Juice, Parsley', 220, 7.0, 6.0, 160.0, 31.0),
('Borsch', 'Russia', 'Beetroot and vegetable soup served with Greek yogurt.', 'Beetroot, Cabbage, Carrots, Tomatoes, Garlic, Dill, Non-Fat Greek Yogurt, Lemon Juice', 150, 2.5, 28.0, 85.0, 5.0),
('Shchi', 'Russia', 'Cabbage soup with potatoes and herbs.', 'Cabbage, Potatoes, Carrots, Onions, Garlic, Dill, Parsley, Olive Oil', 140, 3.0, 26.0, 75.0, 4.0),
('Kerabu Mangga', 'Malaysia', ' green mango salad tossed with herbs, lime, and crushed peanuts.', 'Green Mango, Shallots, Cilantro, Chili, Lime Juice, Crushed Peanuts, Sesame Oil', 180, 8.0, 25.0, 60.0, 4.0);